### ISSUE TITLE
Maps Within Observation Showing Wrong Species When Clicked

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/Windshaft-inaturalist#28]
So when you look at an observation, the awesome new maps now show other locations where the same species was observed in the past. However there is a bug in these maps. Example below:

![burroak](https://cloud.githubusercontent.com/assets/7171475/5911369/d38dbeda-a592-11e4-843e-fd4a2403406f.png)

In this observation - http://www.inaturalist.org/observations/424751 - looking at the map when zoomed in you see that another burr oak observation is present just to the north-northeast. Sometimes when you click on the circle you get the popup for the burr oak observation (http://www.inaturalist.org/observations/10718470) but other times, different species show up - like a cabbage white shown above... also a different plant showed up sometimes. And sometimes it shows one only to quickly flicker to the other.  It seems to happen when there are a cluster of observations at the exact same point or very close to it - but interestingly they aren't even from the same day.

I'm not sure yet which conditions set it off but I've seen it happen a couple of other places too.

**Comment by naturalistcharlie** [comment]
and yes i know lepidoptera are not 'true bugs' :)

**Comment by pleary** [comment]
thanks for the report, with screenshot to boot. I suspect the new 'All Observations' layer is causing interference here. We'll check it out

**Comment by naturalistcharlie** [comment]
That makes sense because I've only noticed the issue recently... around
that time the layers were added.

On Mon, Jan 26, 2015 at 7:54 PM, Patrick Leary <notifications@github.com>
wrote:

> thanks for the report, with screenshot to boot. I suspect the new 'All
> Observations' layer is causing interference here. We'll check it out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/Windshaft-inaturalist/issues/28#issuecomment-71570625>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by pleary** [comment]
A fix for this is now committed and ready to be deployed

**Comment by pleary** [comment]
OK I think this one is finally fixed and deployed. If anyone notices any more problems like this, feel free to re-open it and link to the failing example
