### ISSUE TITLE
checklisted place boundaries for a taxon

### ISSUE THREAD

**Issue by kueda** [inaturalist/Windshaft-inaturalist#29]
We need the ability to render the boundaries of places that have checklists containing a taxon, i.e. all the places where we know something about the taxon.

- [x] Given a taxon_id in the URL, render all places for listed taxa where place_id = the place id and taxon_id = the taxon id
- [x] Should only render places where admin_level is set
- [x] Have 3 tiers of admin_levels that show up depended on zoom, somewhat like we do for observation grids and points, i.e. zoomed all the way out just show admin_level = 0, all the way in admin_level = 3, with 1 and 2 somewhere in between. This will never be perfect b/c admin level doesn't correspond to amount of geographic area, but give it a shot
- [x] Accept an arbitrary color value

Cartography (up for debate)
- [x] confirmed (last_observation_id set): full color
- [x] unconfirmed: a faded version of the requested color (decreased lightness in HSL)
- [x] absent: gray
- [x] introduced: dashed border

For reference, here's what our previous TileStache / Polymaps version looked like:

![screen_shot_2015-02-26_at_12 01 35_pm](https://cloud.githubusercontent.com/assets/22691/6400763/1c25d17a-bdb0-11e4-9ba3-d7489142f5e8.png)

Didn't have the taxon-specific colors. Maybe the green / yellow cartography is better, not sure.

**Comment by pleary** [comment]
What is the best way to determine unconfirmed, absent, and introduced?

**Comment by loarie** [comment]
listed_taxa have establishment_means columns for endemic/native/introduced, occurrence_status columns for absent, and first_observation_id/last_observation_id for unconfirmed/confirmed (ie if there's an obs its confirmed)

**Comment by loarie** [comment]
hmm - I guess for unconfirmed/confirmed we're going on the presence of RG obs. So not sure where that's stored among the Listed_taxa observation stats. I can look into it, but Ken-ichi would prob know off hand.

**Comment by kueda** [comment]
We usually define confirmed as `ListedTaxon#last_observation_id` not being nil. The old logic for this is at https://github.com/inaturalist/inaturalist/blob/master/app/assets/javascripts/taxa/map.polymaps.js#L30

**Comment by pleary** [comment]
I have a few screenshots for people to check out.

Here are colors like the original maps:
![screen shot 2015-03-03 at 11 21 59 am](https://cloud.githubusercontent.com/assets/48566/6466729/b73c47e4-c197-11e4-9d70-b72eca8765bc.png)

Same color for regions, but opacity changed and darker border to represent confirmed/unconfirmed:
![screen shot 2015-03-03 at 11 20 22 am](https://cloud.githubusercontent.com/assets/48566/6466744/d3a7cb92-c197-11e4-8e11-75d4fe2da5d0.png)

Another taxon/place with dashed borders and an absent county. It's hard to see the dashed borders of the unconfirmed regions. Also, the opacity of overlapping regions makes some borders seem faded.
![screen shot 2015-03-03 at 11 22 39 am](https://cloud.githubusercontent.com/assets/48566/6466792/277fd548-c198-11e4-8142-88a8a5ad5ef7.png)

**Comment by kueda** [comment]
Hm, not a huge fan of the opacity or border approaches. I say commit what
you've got based on the original cartography and we can tweak from there.
