### ISSUE TITLE
observations not showing up on species map

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/Windshaft-inaturalist#37]
I noticed that some newer observations are not showing up on species maps, for instance, this black oak observation: http://www.inaturalist.org/observations/1918359 does not show up on the species range map at http://www.inaturalist.org/taxa/49006-Quercus-velutina . It does, however, show up here: http://www.inaturalist.org/observations?taxon_id=49006 .  It may just be some sort of indexing lag or something but I thought it was worth reporting.  I use these species maps a lot, not sure how much others do, but I love them thus me noticing these small delays.

**Comment by naturalistcharlie** [comment]
Also true for http://www.inaturalist.org/observations/1918469 and probably anything else I saw that day.

**Comment by pleary** [comment]
This was probably related to the Elasticsearch replica going down. We now have monitoring on that so we shouldn't have mysterious lag anymore
